#! /bin/sh

# Autostart

xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh
setxkbmap -layout gb,de -option 'grp:alt_shift_toggle'
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

bspc monitor eDP1 -d I II III IV V

bspc config focus_follows_pointer true
bspc config border_width         1
bspc config window_gap		4
bspc config split_ratio          0.52
bspc config top_padding		0

bspc rule -a Zathura state=tiled
